# Generated by Django 4.2.7 on 2023-11-24 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requireddocument',
            name='employee',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='base.employee'),
        ),
    ]
