# Generated by Django 4.2.7 on 2023-11-27 07:48

import base.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_requireddocument_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immigration',
            fields=[
                ('id', models.CharField(default=base.models.generate_unique_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('document_type', models.CharField(blank=True, choices=[('Passport', 'Passport'), ('Visa', 'Visa')], max_length=100, null=True)),
                ('passport_visa_no', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('date_of_expiry', models.DateField()),
                ('citizenship', django_countries.fields.CountryField(max_length=2)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('document', models.FileField(upload_to=base.models.get_upload_path)),
                ('employee', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
    ]
