# Generated by Django 4.2.7 on 2023-12-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_attendance_delete_employeeattendence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='in_Date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='out_Date',
        ),
    ]
