# Generated by Django 4.2.7 on 2023-12-01 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_department_slug_department_department_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department',
            new_name='department_name',
        ),
    ]
