# Generated by Django 4.2.7 on 2023-12-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_department_department_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation',
            old_name='designation',
            new_name='designation_name',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='slug',
        ),
        migrations.AddField(
            model_name='designation',
            name='designation_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
