# Generated by Django 4.2.7 on 2023-11-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_immigration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immigration',
            old_name='passport_visa_no',
            new_name='passport_or_visa_no',
        ),
    ]
