# Generated by Django 4.2.7 on 2023-11-27 10:55

import base.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_passport_visa_no_immigration_passport_or_visa_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.CharField(default=base.models.generate_unique_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(choices=[('HDFC', 'HDFC Bank'), ('ICICI', 'ICICI Bank'), ('SBI', 'State Bank of India'), ('Axis', 'Axis Bank'), ('Kotak', 'Kotak Mahindra Bank'), ('BOB', 'Bank of Baroda'), ('PNB', 'Punjab National Bank'), ('Other', 'Other')], max_length=100)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('IFSC_code', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='IFSC code must be in valid format.', regex='^[A-Za-z]{4}\\d{7}$')])),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
    ]
