# Generated by Django 4.2.7 on 2023-12-01 11:21

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_designation_designation_designation_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendence',
            fields=[
                ('id', models.CharField(default=base.models.generate_unique_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('in_Time', models.TimeField()),
                ('in_Date', models.DateField()),
                ('out_Time', models.TimeField()),
                ('out_Date', models.DateField()),
                ('in_Location', models.CharField(blank=True, max_length=200, null=True)),
                ('out_Location', models.CharField(blank=True, max_length=200, null=True)),
                ('employee', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
    ]
