# Generated by Django 4.2.7 on 2023-11-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_bankdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='status',
        ),
    ]
