# Generated by Django 4.2.7 on 2023-12-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_employeeattendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendence',
            name='month',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employeeattendence',
            name='year',
            field=models.PositiveSmallIntegerField(default=2023),
        ),
    ]
