# Generated by Django 4.2.7 on 2023-12-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_employeeattendence_month_employeeattendence_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendence',
            name='in_Date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeattendence',
            name='in_Time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeattendence',
            name='out_Date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeattendence',
            name='out_Time',
            field=models.CharField(max_length=50),
        ),
    ]
