# Generated by Django 4.2.7 on 2023-12-02 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_employeeattendence_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendence',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee'),
        ),
    ]
