# Generated by Django 4.2.7 on 2023-12-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_employeeattendence_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendence',
            name='in_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeeattendence',
            name='in_Time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='employeeattendence',
            name='out_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeeattendence',
            name='out_Time',
            field=models.TimeField(),
        ),
    ]
