# Generated by Django 4.2.7 on 2023-12-04 05:56

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_employeeattendence_in_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMaster',
            fields=[
                ('id', models.CharField(default=base.models.generate_unique_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('leave_name', models.CharField(max_length=50, unique=True)),
                ('leave_code', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('paid_leave', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
