# Generated by Django 4.2.7 on 2023-12-05 09:25

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_leavemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.CharField(default=base.models.generate_unique_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('period', models.SmallIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
                ('leave_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.leavemaster')),
            ],
        ),
    ]
