# Generated by Django 4.2.7 on 2023-12-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_leaveapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=50, null=True),
        ),
    ]
